version: 1
disable_existing_loggers: False
formatters:
  simple:
      format: "%(message)s"
  error:
      format: "%(asctime)s [%(name)s] [%(levelname)s] :%(levelno)s: %(message)s"

handlers:
  console:
      class: logging.StreamHandler # print to console
      level: DEBUG
      formatter: simple
      stream: ext://flask.logging.wsgi_errors_stream # listen flask
  info_file_handler:
      class: logging.handlers.RotatingFileHandler # print to file
      level: INFO
      formatter: simple
      filename: ./logs/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20 #most 20 extensions
      encoding: utf8
  error_file_handler:
      class: logging.handlers.RotatingFileHandler # print to file
      level: ERROR
      formatter: error
      filename: ./logs/errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
# enable handler
root:
  level: INFO
  handlers: [console,info_file_handler,error_file_handler]